artifact_uri: file:///Users/larry/house-price-regression/mlflow/587131143621536875/ffde3c49bb5b43779a5d9cae76ed29c2/artifacts
end_time: 1771863507963
entry_point_name: ''
experiment_id: '587131143621536875'
lifecycle_stage: active
run_id: ffde3c49bb5b43779a5d9cae76ed29c2
run_name: vaunted-rook-275
source_name: ''
source_type: 4
source_version: ''
start_time: 1771863501583
status: 3
tags: []
user_id: larry
