artifact_uri: file:///Users/larry/house-price-regression/mlflow/587131143621536875/a0cfd6fbb3c749a28cd98b0fd6f59216/artifacts
end_time: 1771625834099
entry_point_name: ''
experiment_id: '587131143621536875'
lifecycle_stage: active
run_id: a0cfd6fbb3c749a28cd98b0fd6f59216
run_name: agreeable-vole-502
source_name: ''
source_type: 4
source_version: ''
start_time: 1771625811788
status: 3
tags: []
user_id: larry
