artifact_uri: file:///Users/larry/house-price-regression/mlflow/587131143621536875/dcbddb33b20d4c6da42429e48507b2ed/artifacts
end_time: 1771862683620
entry_point_name: ''
experiment_id: '587131143621536875'
lifecycle_stage: active
run_id: dcbddb33b20d4c6da42429e48507b2ed
run_name: flawless-cod-377
source_name: ''
source_type: 4
source_version: ''
start_time: 1771862663743
status: 3
tags: []
user_id: larry
