artifact_uri: file:///Users/larry/house-price-regression/mlflow/587131143621536875/a4ffd4bbca85455f8b572a99ce68df44/artifacts
end_time: 1771625574987
entry_point_name: ''
experiment_id: '587131143621536875'
lifecycle_stage: active
run_id: a4ffd4bbca85455f8b572a99ce68df44
run_name: wise-pig-623
source_name: ''
source_type: 4
source_version: ''
start_time: 1771625574980
status: 4
tags: []
user_id: larry
