artifact_uri: file:///Users/larry/house-price-regression/mlflow/587131143621536875/cdebd1619e304a70bbfcee28d6ca3bb1/artifacts
end_time: 1771862342800
entry_point_name: ''
experiment_id: '587131143621536875'
lifecycle_stage: active
run_id: cdebd1619e304a70bbfcee28d6ca3bb1
run_name: silent-loon-521
source_name: ''
source_type: 4
source_version: ''
start_time: 1771862317346
status: 3
tags: []
user_id: larry
