artifact_uri: file:///Users/larry/house-price-regression/mlflow/587131143621536875/b1b2bdc2a30f4a61b05bdaf009e6a18e/artifacts
end_time: 1771863135633
entry_point_name: ''
experiment_id: '587131143621536875'
lifecycle_stage: active
run_id: b1b2bdc2a30f4a61b05bdaf009e6a18e
run_name: puzzled-hound-719
source_name: ''
source_type: 4
source_version: ''
start_time: 1771863097879
status: 3
tags: []
user_id: larry
